### ISSUE TITLE
Error and add output file as features

### ISSUE THREAD

**Issue by mohammed-sec2010** [xyele/igoturls#1]
Hi

greate tools but I have problem when I run this below command:

cat urls.txt | while read url; do python3 igoturls.py ""$url""   ; done > igoturls.txt;

output:
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 435, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 226, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 486, in read_chunked
    self._update_chunk_length()
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 439, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 660, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 340, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 514, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "igoturls.py", line 40, in getCommoncrawl
    [[urls.append(fix(json.loads(x)["url"])) for x in request(i+"?url=*.{}/*&output=json".format(domain)).split("\n")[:-1]] for i in getDB]
  File "igoturls.py", line 40, in <listcomp>
    [[urls.append(fix(json.loads(x)["url"])) for x in request(i+"?url=*.{}/*&output=json".format(domain)).split("\n")[:-1]] for i in getDB]
  File "igoturls.py", line 12, in request
    return requests.get(req, verify=False,allow_redirects=False).text
  File "/usr/lib/python3/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 620, in send
    r.content
  File "/usr/lib/python3/dist-packages/requests/models.py", line 737, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 663, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by mohammed-sec2010** [comment]
urls.txt have multiple domains :

**Comment by xyele** [comment]
that looks working for me, could you please run your command again?

note: i'm gonna release new version for making igoturls more stable as soon as can possible.

**Comment by mohammed-sec2010** [comment]
it is not working in https://www.katacoda.com/courses/ubuntu/playground    and ubuntu subsystem

**Comment by mohammed-sec2010** [comment]
Hi
I solved the problem by adding this below code before the print line :)
sys.stdout = open("1.txt", "a")
